
all: ejemplo09-bloques \
	 ejemplo09-mod


ejemplo09-bloques : ejemplo09-bloques.cpp
	g++ -std=c++11 -pthread -O3 ejemplo09-bloques.cpp -o ejemplo09-bloques

ejemplo09-mod : ejemplo09-mod.cpp
	g++ -std=c++11 -pthread -O3 ejemplo09-mod.cpp -o ejemplo09-mod
